### ISSUE TITLE
Spaces / TABS

### ISSUE THREAD

**Issue by haakonnessjoen** [monoxane/companion-module-propresenter6#1]
https://github.com/monoxane/companion-module-propresenter6/blob/73cfb3fcceddfb29ec053a7cecdf266fd5419013/index.js#L87

Tip: For inclusion in Companion. Please fix your spaces/tabs. All indentation should be done with TAB characters. Aligning text mid-line is done with spaces though.

**Comment by monoxane** [comment]
Yeap, It'll be done tomorrow, I just wanted to get something out for people to test tonight before I go to sleep. (and I have admittedly really shocking tab/space consistency so I need to work on that in general)

**Comment by monoxane** [comment]
I think I fixed it all
